# Generated by Django 4.2 on 2023-05-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('category', models.TextField(choices=[('AR', 'Art'), ('RP', 'Realistic Picture'), ('O', 'Other')], max_length=2)),
                ('image', models.ImageField(upload_to='Product')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
