# Generated by Django 4.2 on 2023-06-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
