# Generated by Django 4.2 on 2023-06-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_order_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
